stages:
  - build

variables:
  CI_REGISTRY: "docker.io"  # Docker Hub registry

# Build stage
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind  # Docker-in-Docker เพื่อให้สามารถใช้งาน Docker ภายใน CI/CD pipeline ได้
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker buildx create --use  # สร้าง buildx builder instance และใช้มัน
  script:
    - docker buildx build --platform linux/amd64 -t $DOCKERHUB_USERNAME/order-service:1.0 --push .  # สร้าง image และ push
  only:
    - develop  # ทำงานเมื่อ push บน branch 'develop'